server:
  servlet:
    context-path: /shopping
  port: 8080

spring:
  #  前端
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html

  #    mysql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  #    AOP
  aop:
    auto: true

  #      Redis
  redis:
    host: 127.0.0.1
#    host: 49.232.175.201
    port: 6379
#    password: 123456
    password:
    jedis:
      pool:
        max-active: 50
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 60000
    database: 0
#    邮件服务
  mail:
    host: smtp.qq.com
    port: 587
    username: tongxin0925@qq.com
    password: twoacljxrjczbdhi
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.app.shopping.model

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
#邮件发件人
mail:
  fromMail:
    addr: shopping@qq.com

#文件上传路径
files:
  upload:
    path: /users/t_t/IdeaProjects/demo/src/main/resources/static
